### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hbooo** [Cr4zyy/Sonarr-Transmission-Fixer#1]
Hello, 

I'm trying to use your script on my nas synology but I got a permission denied : 
Unable to send OnDownload notification to: SonarrTransmission: ApplicationName='/mypathto/SonarrTransmission.sh', CommandLine='', CurrentDirectory='', Native error= Access denied

Can you tell me what kind of permission I need to define on which folder and for which user?

Thanks in advance

**Comment by Cr4zyy** [comment]
My script runs as the same user that my Sonarr install is run under and has 744 permissions. Best bet is probably making sure that the script is executable by the Sonarr user.
